# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15y3egYRXPAfbLS_GbJnH06piolsH0P68
"""

# app.py
import streamlit as st
import pandas as pd
import numpy as np
import re
import streamlit as st
import matplotlib.pyplot as plt
from matplotlib.ticker import FuncFormatter
import plotly.graph_objects as go
import plotly.express as px

# ------------------------------
# Configuração do app
# ------------------------------
st.set_page_config(layout='wide', page_icon="assets/icons/OIP.png")

# ------------------------------
# Carregamento do arquivo local
# ------------------------------
EXCEL_PATH = "consolidado.xlsx"

@st.cache_data(show_spinner=False)
def carregar_excel_local(caminho):
    """Carrega Excel local com múltiplas abas e retorna um dicionário de DataFrames"""
    try:
        xls = pd.read_excel(caminho, sheet_name=None)
        return xls
    except Exception as e:
        st.error(f"Erro ao carregar Excel: {e}")
        st.stop()

rede = carregar_excel_local(EXCEL_PATH)

# ------------------------------
# Função de limpeza de moeda
# ------------------------------
def limpar_moeda(valor):
    """Limpa valores monetários no formato R$ 1.234,56 -> 1234.56"""
    if pd.isna(valor):
        return 0.0
    if isinstance(valor, (int, float, np.number)):
        return valor
    if isinstance(valor, str):
        v = valor.strip()
        if v in ("-", ""):
            return 0.0
        v = v.replace("R$", "").replace("r$", "").strip()
        v = re.sub(r"\.(?=\d{3},)", "", v)
        v = v.replace(",", ".")
        try:
            return float(v)
        except:
            return 0.0
    return 0.0

# ------------------------------
# Colunas que precisam de conversão
# ------------------------------
colunas_para_converter = [
    'Real', 'Meta Mês', 'Ticket Médio',
    'Novo', 'Refin', 'PORT + Refin da Port >=1,85',
    'Refin da Port < 1,85', 'Rep. Legal', 'META AUMENTO MARGEM'
]

# ------------------------------
# Aplica função de limpeza a todas as abas
# ------------------------------
for nome_aba, df in rede.items():
    for col in colunas_para_converter:
        if col in df.columns and df[col].dtype == object:
            df[col] = df[col].apply(limpar_moeda)
    rede[nome_aba] = df  # garante atualização no dicionário

# ---------- CONVERTER COLUNA DE DATAS ---------- #
for nome_aba, df in rede.items():
    if 'Data' in df.columns:
        df['Data'] = pd.to_datetime(df['Data'], errors='coerce')
        rede[nome_aba] = df

# ---------- FUNÇÃO ADICIONAR DIAS ---------- #
def adicionar_dias(df):
    df = df.copy()
    if 'Data' in df.columns and 'Nome_Loja' in df.columns:
        df['ano_mes'] = df['Data'].dt.to_period('M')
        contagem = df.groupby(['Nome_Loja', 'ano_mes']).size().rename('DIAS')
        df = df.join(contagem, on=['Nome_Loja', 'ano_mes'])
        df = df.drop(columns=['ano_mes'])
    return df

# ---------- APLICAR FUNÇÃO EM TODAS AS ABAS ---------- #
for nome_aba, df in rede.items():
    rede[nome_aba] = adicionar_dias(df)

# ---------- PREENCHER META MÊS ---------- #
def preencher_meta_mes(df):
    df = df.copy()
    if 'Data' in df.columns and 'Nome_Loja' in df.columns and 'Meta Mês' in df.columns:
        df['ano_mes'] = df['Data'].dt.to_period('M')
        df['Meta Mês'] = (
            df['Meta Mês'].replace(0, pd.NA)
            .groupby([df['Nome_Loja'], df['ano_mes']])
            .transform(lambda x: x.bfill())
            .fillna(0)
        )
        df = df.drop(columns=['ano_mes'])
    return df

# Aplica a todas as abas
for nome_aba, df in rede.items():
    rede[nome_aba] = preencher_meta_mes(df)

# ---------- CALCULAR VARIAÇÃO ---------- #
def calcular_variacao(df):
    df = df.copy()
    if 'Data' in df.columns and 'Nome_Loja' in df.columns and 'Real' in df.columns:
        df["data_aux"] = df['Data']
        df["ano_mes"] = df["data_aux"].dt.to_period("M")
        df = df.sort_values(["Nome_Loja", "ano_mes", "data_aux"])

        def variacao_grupo(x):
            var = x - x.shift(1)
            var.iloc[0] = x.iloc[0]
            return var

        df["Real_Variacao"] = df.groupby(["Nome_Loja", "ano_mes"])["Real"].transform(variacao_grupo)
        df = df.drop(columns=["ano_mes", "data_aux"], errors='ignore')
    return df

# Aplica a todas as abas
for nome_aba, df in rede.items():
    rede[nome_aba] = calcular_variacao(df)

# ---------- CALCULAR META DIA ---------- #
def calcular_meta_dia(df):
    df = df.copy()
    if 'Meta Mês' in df.columns and 'DIAS' in df.columns:
        df['Meta Dia'] = df['Meta Mês'] / df['DIAS']
    return df

# Aplica a todas as abas
for nome_aba, df in rede.items():
    rede[nome_aba] = calcular_meta_dia(df)

rede = pd.concat(
    [df.assign(Produto=nome) for nome, df in rede.items()]
)

import streamlit as st
import pandas as pd
import numpy as np
import plotly.graph_objects as go
import plotly.express as px
from matplotlib import pyplot as plt
from matplotlib.ticker import FuncFormatter

# ------------------------------------------------------
# INÍCIO — TÍTULO PRINCIPAL
# ------------------------------------------------------
st.title("Desempenho Comercial")

paginas = [
    "Consolidado",
    "Ranking e Metas"
]

pagina = st.selectbox("Selecione a página:", paginas)

# ------------------------------------------------------
# FUNÇÕES COMPARTILHADAS (para ambas as páginas)
# ------------------------------------------------------

def format_large_numbers(value):
    if value is None or pd.isna(value):
        return ""
    return f"R$ {value:,.0f}".replace(",", ".")


def filtrar_df(rede, produto, regional, coordenador, loja, mes, ano):
    df_f = rede.copy()

    if produto != 'Todos':
        df_f = df_f[df_f['Produto'] == produto]
    if regional != 'Todas':
        df_f = df_f[df_f['Regional'] == regional]
    if coordenador != 'Todos':
        df_f = df_f[df_f['Coordenador'] == coordenador]
    if loja != 'Todas':
        df_f = df_f[df_f['Nome_Loja'] == loja]

    df_f = df_f[(df_f['Data'].dt.year == int(ano)) &
                (df_f['Data'].dt.month == int(mes))]

    return df_f


def calcular_acumulados(df_filtrado):
    df_grouped = df_filtrado.groupby('Data', as_index=False).agg({
        'DIAS': 'sum',
        'Real_Variacao': 'sum',
        'Meta Dia': 'sum'
    }).sort_values('Data').reset_index(drop=True)

    df_grouped['REAL_ACUM'] = df_grouped['Real_Variacao'].cumsum()
    df_grouped['META_ACUM'] = df_grouped['Meta Dia'].cumsum()

    df_grouped['DESVIO_DIA_PCT'] = (
        (df_grouped['Real_Variacao'] - df_grouped['Meta Dia']) /
        df_grouped['Meta Dia'].replace(0, np.nan) * 100
    ).fillna(0)

    df_grouped['DESVIO_ACUM'] = df_grouped['REAL_ACUM'] - df_grouped['META_ACUM']

    df_grouped['DESVIO_ACUM_PCT'] = (
        (df_grouped['REAL_ACUM'] - df_grouped['META_ACUM']) /
        df_grouped['META_ACUM'].replace(0, np.nan) * 100
    ).fillna(0)

    return df_grouped


def aplicar_estilo(fig):
    fig.update_layout(
        template="plotly_white",
        autosize=True,
        dragmode=False,
        legend=dict(
            orientation="h",
            yanchor="bottom",
            y=1,
            xanchor="left",
            x=0,
            bgcolor="rgba(255,255,255,0.5)",
            bordercolor="rgba(0,0,0,0.15)",
            borderwidth=1
        ),
        margin=dict(l=10, r=10, t=120, b=10),
        font=dict(size=12)
    )
    fig.update_xaxes(tickangle=30, automargin=True)
    fig.update_yaxes(automargin=True)
    return fig


# =====================================================
# FUNÇÃO DOS GRÁFICOS 2x2 (CONSOLIDADO)
# =====================================================
def plot_2x2(df_grouped, produto, mes, ano):

    st.subheader(f"{produto} — {mes}/{ano}")

    if not pd.api.types.is_datetime64_any_dtype(df_grouped["Data"]):
        df_grouped["Data"] = pd.to_datetime(df_grouped["Data"])

    first_day = pd.Timestamp(year=ano, month=mes, day=1)
    last_day = first_day + pd.offsets.MonthEnd(0)
    full_dates = pd.DataFrame({"Data": pd.date_range(first_day, last_day, freq="D")})

    df = full_dates.merge(df_grouped, on="Data", how="left")
    df["DataLabel"] = df["Data"].dt.strftime("%d/%m")

    df = df[~(df["Real_Variacao"].isna() & df["Meta Dia"].isna())]

    modo = st.radio(
        "Selecione a visualização:",
        ["Diário", "Acumulado"],
        horizontal=True
    )

    # ------- DIÁRIO -------
    if modo == "Diário":
        df["DesvioLabel"] = df["DESVIO_DIA_PCT"].apply(lambda x: "Positivo" if x >= 0 else "Negativo")

        fig1 = go.Figure()
        fig1.add_bar(
            x=df["DataLabel"],
            y=df["Real_Variacao"],
            name='Real Dia',
            marker_color='#EA9411'
        )
        fig1.add_scatter(
            x=df["DataLabel"],
            y=df["Meta Dia"],
            mode='lines+markers',
            name='Meta Dia',
            marker=dict(color='blue')
        )
        fig1.update_layout(title="Diário (R$)", xaxis_title="Data")
        fig1 = aplicar_estilo(fig1)
        st.plotly_chart(fig1, use_container_width=True)

        fig2 = go.Figure()
        fig2.add_bar(
            x=df["DataLabel"],
            y=df["DESVIO_DIA_PCT"],
            marker_color=["#EA9411" if x >= 0 else "gray" for x in df["DESVIO_DIA_PCT"]]
        )
        fig2.add_hline(y=0, line_color="blue")
        fig2.update_layout(title="Desvio Diário (%)")
        fig2 = aplicar_estilo(fig2)
        st.plotly_chart(fig2, use_container_width=True)

    # ------- ACUMULADO -------
    else:
        df["DesvioAcumLabel"] = df["DESVIO_ACUM"].apply(lambda x: "Positivo" if x >= 0 else "Negativo")

        fig3 = go.Figure()
        fig3.add_bar(
            x=df["DataLabel"],
            y=df["REAL_ACUM"],
            name='Real Acumulado',
            marker_color='#EA9411'
        )
        fig3.add_scatter(
            x=df["DataLabel"],
            y=df["META_ACUM"],
            mode='lines+markers',
            name='Meta Acumulada',
            marker=dict(color='blue')
        )
        fig3.update_layout(title="Acumulado (R$)")
        fig3 = aplicar_estilo(fig3)
        st.plotly_chart(fig3, use_container_width=True)

        fig4 = go.Figure()
        fig4.add_bar(
            x=df["DataLabel"],
            y=df["DESVIO_ACUM"],
            marker_color=["#EA9411" if x >= 0 else "gray" for x in df["DESVIO_ACUM"]]
        )
        fig4.add_hline(y=0, line_color="blue")
        fig4.update_layout(title="Desvio Acumulado (R$)")
        fig4 = aplicar_estilo(fig4)
        st.plotly_chart(fig4, use_container_width=True)



# ------------------------------------------------------
# ###############   PÁGINA 1 — CONSOLIDADO   ###############
# ------------------------------------------------------

if pagina == "Consolidado":

    st.header("Consolidado")

    # ------------- SIDEBAR -------------
    st.sidebar.header("Filtros")

    produtos = ['Todos'] + sorted(rede['Produto'].dropna().unique().tolist())
    produto_sel = st.sidebar.selectbox("Produto", produtos, index=0)

    regionais = ['Todas'] + sorted(rede['Regional'].dropna().unique().tolist())
    regional_sel = st.sidebar.selectbox("Regional", regionais, index=0)

    df_reg = rede.copy()
    if regional_sel != 'Todas':
        df_reg = df_reg[df_reg['Regional'] == regional_sel]

    coordenadores = ['Todos'] + sorted(df_reg['Coordenador'].dropna().unique().tolist())
    coordenador_sel = st.sidebar.selectbox("Coordenador", coordenadores, index=0)

    df_coord = df_reg.copy()
    if coordenador_sel != 'Todos':
        df_coord = df_coord[df_coord['Coordenador'] == coordenador_sel]

    lojas = ['Todas'] + sorted(df_coord['Nome_Loja'].dropna().unique().tolist())
    loja_sel = st.sidebar.selectbox("Loja", lojas, index=0)

    anos = sorted(rede['Data'].dt.year.unique().tolist())
    anos_sel = st.sidebar.selectbox("Ano", anos, index=len(anos)-1)

    meses = sorted(rede['Data'].dt.month.unique().tolist())
    mes_sel = st.sidebar.selectbox("Mês", meses, index=0)

    # ------------ PROCESSAR DADOS ------------
    df_f = filtrar_df(rede, produto_sel, regional_sel, coordenador_sel, loja_sel, mes_sel, anos_sel)

    if df_f.empty:
        st.warning("Nenhum dado após aplicar os filtros.")
        st.stop()

    df_grouped = calcular_acumulados(df_f)

    st.markdown(
        f"**Produto:** {produto_sel}  •  **Regional:** {regional_sel}  •  "
        f"**Coordenador:** {coordenador_sel}  •  **Loja:** {loja_sel}  •  "
        f"**Período:** {mes_sel}/{anos_sel}"
    )

    # ------------ PLOTAR GRÁFICOS ------------
    plot_2x2(df_grouped, produto_sel, mes_sel, anos_sel)

    # ------------ TABELA FINAL ------------
    st.subheader("Tabela Consolidada")

    df_exibir = df_grouped.copy()
    if "DIAS" in df_exibir.columns:
        df_exibir = df_exibir.drop(columns=["DIAS"])

    df_exibir = df_exibir.rename(columns={
        "DESVIO_DIA_PCT": "Desvio Dia %",
        "DESVIO_ACUM_PCT": "Desvio Acumulado %"
    })

    df_exibir["Desvio Dia %"] = df_exibir["Desvio Dia %"].apply(lambda x: f"{x:.2f}%")
    df_exibir["Desvio Acumulado %"] = df_exibir["Desvio Acumulado %"].apply(lambda x: f"{x:.2f}%")

    df_exibir['Producao Dia'] = df_exibir['Real_Variacao'].apply(format_large_numbers)
    df_exibir['Meta Dia'] = df_exibir['Meta Dia'].apply(format_large_numbers)
    df_exibir['Producao Acumulada'] = df_exibir['REAL_ACUM'].apply(format_large_numbers)
    df_exibir['Meta Acumulada'] = df_exibir['META_ACUM'].apply(format_large_numbers)
    df_exibir['Desvio Acumulado'] = df_exibir['DESVIO_ACUM'].apply(format_large_numbers)

    st.dataframe(df_exibir, use_container_width=True)

    df_csv = df_grouped.copy()
    if "DIAS" in df_csv.columns:
        df_csv = df_csv.drop(columns=["DIAS"])
    df_csv = df_csv.rename(columns={
        "DESVIO_DIA_PCT": "Desvio Dia %",
        "DESVIO_ACUM_PCT": "Desvio Acumulado %"
    })

    csv = df_csv.to_csv(index=False).encode('utf-8-sig')

    st.download_button(
        label="📥 Baixar tabela em CSV",
        data=csv,
        file_name=f"consolidado_{mes_sel}_{anos_sel}.csv",
        mime="text/csv"
    )


# ------------------------------------------------------
# ###############   PÁGINA 2 — RANKING E METAS   ###############
# ------------------------------------------------------

elif pagina == "Ranking e Metas":

    st.header("Ranking e Metas")

    # ------------------ SIDEBAR ------------------
    st.sidebar.header("Filtros — Ranking")

    # REGIONAL
    regionais = ['Todas'] + sorted(rede['Regional'].dropna().unique().tolist())
    regional_widget = st.sidebar.selectbox("Regional", regionais, index=0, key="rank_reg")

    # COORDENADOR (filtrado pela regional)
    df_reg = rede.copy()
    if regional_widget != 'Todas':
        df_reg = df_reg[df_reg['Regional'] == regional_widget]

    coordenadores = ['Todos'] + sorted(df_reg['Coordenador'].dropna().unique().tolist())
    coordenador_widget = st.sidebar.selectbox("Coordenador", coordenadores, index=0, key="rank_coord")

    # PRODUTO (filtrado pela regional + coordenador)
    df_coord = df_reg.copy()
    if coordenador_widget != 'Todos':
        df_coord = df_coord[df_coord['Coordenador'] == coordenador_widget]

    produtos = ['Todos'] + sorted(df_coord['Produto'].dropna().unique().tolist())
    produto_widget = st.sidebar.selectbox("Produto", produtos, index=0, key="rank_prod")

    # ANO / MÊS
    anos = sorted(rede['Data'].dt.year.unique().tolist())
    ano_widget = st.sidebar.selectbox("Ano", anos, index=len(anos)-1, key="rank_ano")

    meses = sorted(rede['Data'].dt.month.unique().tolist())
    mes_widget = st.sidebar.selectbox("Mês", meses, index=0, key="rank_mes")

    # ----------------------------------------------------
    # Função do ranking (Plotly)
    # ----------------------------------------------------
    def plot_ranking(produto, regional, coordenador, mes, ano):
        df_f = rede.copy()

        if regional != 'Todas':
            df_f = df_f[df_f['Regional'] == regional]

        if coordenador != 'Todos':
            df_f = df_f[df_f['Coordenador'] == coordenador]
            grupo = 'Nome_Loja'
        else:
            grupo = 'Coordenador'

        if produto != 'Todos':
            df_f = df_f[df_f['Produto'] == produto]

        df_f = df_f[(df_f['Data'].dt.month == mes) & (df_f['Data'].dt.year == ano)]

        if df_f.empty:
            st.warning("Nenhum dado após aplicar os filtros.")
            return

        ranking = df_f.groupby(grupo)[['Real_Variacao', 'Meta Dia']].sum().reset_index()
        ranking.rename(columns={'Real_Variacao': 'Real_Acumulada', 'Meta Dia': 'Meta_Acumulada'}, inplace=True)

        if ranking.empty:
            st.warning("Nenhum dado disponível.")
            return

        ranking.sort_values('Real_Acumulada', ascending=True, inplace=True)

        fig = go.Figure()

        fig.add_bar(
            y=ranking[grupo],
            x=ranking['Real_Acumulada'],
            orientation='h',
            name="Real Acumulado",
            marker_color="#EA9411",
            hovertemplate="<b>%{y}</b><br>Real: %{x:,.0f}<extra></extra>"
        )

        fig.add_scatter(
            y=ranking[grupo],
            x=ranking['Meta_Acumulada'],
            mode='markers',
            name="Meta Acumulada",
            marker=dict(size=12, symbol="diamond", color="blue"),
            hovertemplate="<b>%{y}</b><br>Meta: %{x:,.0f}<extra></extra>"
        )

        fig.update_layout(
            title=f"Ranking {grupo} ({mes}/{ano}) - Regional: {regional}",
            template="plotly_white",
            font=dict(size=12),
            margin=dict(l=40, r=10, t=80, b=40),
            legend=dict(
                orientation="h",
                y=1.05,
                x=0,
                bgcolor="rgba(255,255,255,0.5)",
                bordercolor="rgba(0,0,0,0.15)",
                borderwidth=1
            ),
            width=None, height=None
        )

        st.plotly_chart(fig, use_container_width=True, config={"displayModeBar": False})

    # EXECUTAR GRÁFICO
    plot_ranking(produto_widget, regional_widget, coordenador_widget, mes_widget, ano_widget)
